# Generated by Django 4.1.3 on 2022-12-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_surname', models.CharField(max_length=100, verbose_name='Name and Surname')),
                ('course_name', models.TextField(verbose_name='Course name')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('place', models.CharField(max_length=100, verbose_name='Place')),
                ('course_director', models.CharField(max_length=100, verbose_name='Course director')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
            },
        ),
    ]
