# Generated by Django 4.1.3 on 2022-12-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_certificates'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='cert_id',
            field=models.CharField(default=0, max_length=20, verbose_name='Cert ID'),
            preserve_default=False,
        ),
    ]
