# Generated by Django 4.1.3 on 2022-12-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_certificates_cert_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificates',
            name='id',
        ),
        migrations.AlterField(
            model_name='certificates',
            name='cert_id',
            field=models.CharField(default='8A5DAVNB', max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
