# Generated by Django 4.1.3 on 2022-12-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_certificates_id_alter_certificates_cert_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificates',
            name='cert_id',
        ),
        migrations.AddField(
            model_name='certificates',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
