# Generated by Django 4.1.3 on 2022-12-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_certificates_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='date',
            field=models.DateTimeField(verbose_name='Date'),
        ),
    ]
